name: Build AuthenticationWebApp

on: 
  push:
    branches:
      - features/thussain/*
      
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: 'Checkout code'
      uses: actions/checkout@v4
    
    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 'net10.0-windows'

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build 
    
    - name: Test
      run: dotnet test 


