name: Build AuthenticationWebApp

on:   
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    
    - name: 'Checkout code'
      uses: actions/checkout@v4
    
    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '10.0.x'

    - name: Restore AuthenticationWebApp
      run: dotnet restore AuthenticationUI/AuthenticationUI.csproj

    - name: Build AuthenticationWebApp
      run: dotnet build AuthenticationUI/AuthenticationUI.csproj

    - name: Test AuthenticationWebApp
      run: dotnet test AuthenticationUI/AuthenticationUI.csproj


